WebApplication3/Controllers/CategoriesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebApplication3;
using System.IO;
using Newtonsoft.Json;

namespace WebApplication3.Controllers
{
    public class CategoriesController : Controller
    {
        private NorthwindEntities db = new NorthwindEntities();

        public ActionResult CategoryImage(int? id)
        {
            if (id == null) return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            Category c = db.Categories.Find(id.Value);
            if (c == null) return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            if (c.Picture?.Length == null) return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            var picture = c.Picture.ToArray();
            if (picture[0] == 21) picture = picture.Skip(78).ToArray();
            return File(picture, "image/jpg");
        }

        public string CategoryName(int? id)
        {
            if (id == null) return "";
            Category c = db.Categories.Find(id.Value);
            if (c == null) return "";
            return c.CategoryName;

        }

        public string Category(int? id)
        {
            if (id == null) return null;
            Category c = db.Categories.Find(id.Value);
            if (c == null) return null;
            string s = JsonConvert.SerializeObject(new { c.CategoryID, c.CategoryName, c.Description });
            return s;
        }

        // GET: Categories
        public ActionResult Index(int? id = 0)
        {
            if (id > 0)
            ViewBag.Error = $"Selline kategooia on numbri all {id} juba olemas";
            return View(db.Categories.ToList());
        }

        // GET: Categories/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Category category = db.Categories.Find(id);
            if (category == null)
            {
                return HttpNotFound();
            }
            ViewBag.Tooted = new SelectList(db.Products.Where(x => x.CategoryID == category.CategoryID).ToList(), "ProductID", "ProductName");

            Session["Viimatine"] = category;

            return View(category);
        }

        // GET: Categories/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Categories/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "CategoryID,CategoryName,Description,Picture")] Category category)
        {
            if (ModelState.IsValid)
            {
                var c = db.Categories.Where(x => x.CategoryName == category.CategoryName).FirstOrDefault();
                if (c != null)    return RedirectToAction("Index", new { id = c.CategoryID });
                db.Categories.Add(category);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(category);
        }

        // GET: Categories/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Category category = db.Categories.Find(id);
            if (category == null)
            {
                return HttpNotFound();
            }
            return View(category);
        }

        // POST: Categories/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "CategoryID,CategoryName,Description")] Category category, HttpPostedFileBase file)
        {
            if (ModelState.IsValid)
            {
                db.Entry(category).State = EntityState.Modified;
                db.Entry(category).Property(x => x.Picture).IsModified = false;
                if (file != null && file.ContentLength > 0)
                {
                    using (BinaryReader br = new BinaryReader(file.InputStream))
                    {
                        byte[] buff = br.ReadBytes(file.ContentLength);
                        category.Picture = buff;
                    }
                }
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(category);
        }

        // GET: Categories/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Category category = db.Categories.Find(id);
            if (category == null)
            {
                return HttpNotFound();
            }
            return View(category);
        }

        // POST: Categories/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Category category = db.Categories.Find(id);
            db.Categories.Remove(category);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebApplication3/Views/Categories/Create.cshtml
@model WebApplication3.Category

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Category</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.CategoryName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CategoryName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CategoryName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WebApplication3/Views/Categories/Delete.cshtml
@model WebApplication3.Category

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Category</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CategoryName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CategoryName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Picture)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Picture)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

WebApplication3/Views/Categories/Details.cshtml
@model WebApplication3.Category

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Category</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CategoryName)
        </dt>

        <dd class="form-control"  style="width:400px">
            @Html.DisplayFor(model => model.CategoryName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd class="form-control" style="width:400px">
            @Html.EditorFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Picture)
        </dt>

        <dd>
            @*@Html.DisplayFor(model => model.Picture)*@
            <img src='@Url.Action( "CategoryImage", "Categories", new { id = Model.CategoryID } )' height="80" />

        </dd>

    </dl>
</div>

<div>
<table>
    <tr>
@for (int i = 0; i < 4; i++)
{
        <td id="@i">
            <h4>Selle kategooria tooted</h4>
            @{
                <p>@Html.DropDownList("Tooted", null, "-- vali --" ,htmlAttributes: new { @class = "form-control", onchange = $"TeeMidagi({i})", id = "dropdown" })</p>
                <table>
                    <tr>
                        <td>Nimetus:</td>
                        <td id="nimetus" class="form-control henn">y</td>
                    </tr>
                    <tr>
                        <td>Hind:</td>
                        <td id="hind" class="form-control henn">y</td>
                    </tr>
                    <tr>
                        <td>Laos:</td>
                        <td id="laos" class="form-control henn">y</td>
                    </tr>
                </table>
                <p>Silumisinfo:</p><p id="demo" class="text-danger"></p>
            }

        </td>
 }
 

    </tr>
</table>
</div>

<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.CategoryID }) |
    @Html.ActionLink("Back to List", "Index")
</p>
<script>
    function TeeMidagi(n)
    {
        $('#'+n).find('.henn').text("");
        $.ajax({
            url: "/api/products/" + $('#' + n).find("#dropdown").val(),
            success: function (result)
            {
                $('#' + n).find("#nimetus").text(result.ProductName);
                $('#' + n).find("#hind").text(result.UnitPrice);
                $('#' + n).find("#laos").text(result.UnitsInStock);
            },
            error: function (result) { $("$demo").text("error:" + result);$("$demo").show()}
                    });
    }
</script>

WebApplication3/Views/Categories/Edit.cshtml
@model WebApplication3.Category

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>
@*(Html.BeginForm("Edit","Categories",FormMethod.Post,new { enctype = "multipart/form-data" }))*@

@using (Html.BeginForm(
    "Edit", 
    "Categories", 
    FormMethod.Post, 
    new { enctype = "multipart/form-data" }))
{
                @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>Category</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.CategoryID)
    @Html.DisplayFor(Model => Model.CategoryID, new { @class = "control-label col-md-2" })

    <div class="form-group">
        @Html.LabelFor(model => model.CategoryName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.CategoryName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.CategoryName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextAreaFor(model => model.Description, new { htmlAttributes = new { @class = "form-control", @cols = "80", @rows = "10", height = 100 } })
            @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
        </div>
    </div>

    @*<div class="form-group">
            @Html.LabelFor(model => model.Picture, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Picture, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Picture, "", new { @class = "text-danger" })
            </div>
        </div>*@

 
    <img id="pilt" src='@Url.Action( "CategoryImage", "Categories", new { id = Model.CategoryID } )' height="80" />
    <label for="file">Upload Image:</label>
    <input type="file" name="file" id="file" /><br><br>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
    @Html.ActionLink("Tekst", "Meetod", new {id=7, nimi="Henn", vanus = 63})    
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>

<script>
    function readURL(input) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();

            reader.onload = function (e) {
                $('#pilt').attr('src', e.target.result);
            }
            reader.readAsDataURL(input.files[0]);
        }
    }
   $(document).ready(function () {
        $("#file").change(function () {
            readURL(this);
        });
   });
    
</script>

WebApplication3/Views/Categories/Index.cshtml
@model IEnumerable<WebApplication3.Category>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>

<h1 style="color:red">@ViewBag.Error</h1>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.CategoryName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Picture)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.CategoryName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Description)
        </td>
        <td>
            @*@Html.DisplayFor(modelItem => item.Picture)*@
            <img src='@Url.Action( "CategoryImage", "Categories", new { id = item.CategoryID } )' height="80" />
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.CategoryID }) |
            @Html.ActionLink("Details", "Details", new { id=item.CategoryID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.CategoryID })
        </td>
    </tr>
}

</table>